### ISSUE TITLE
Add the ability to change the matching type of command sets

### ISSUE THREAD

**Issue by TheJoshue** [lokka30/CommandDefender#9]
```yml
sets:
  - mode: DENY
    type: EQUALS
    list:
      - '/plugins'
```
Add the ability to change the matching type (`type`).
Possible values: `EQUALS`, `!EQUALS`, `STARTSWITH`, `!STARTSWITH`, `CONTAINS`, `!CONTAINS`
